import { Processor, WorkerHost } from '@nestjs/bullmq';
import { Job } from 'bullmq';
import { Inject, Logger } from '@nestjs/common';
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { QUEUES, JOBS } from '@taxai/shared';
import { AppConfigService } from '../../../api/src/infrastructure/config/app-config.service';
import { IFilingRepository, FILING_REPOSITORY } from '../../../api/src/domain/repositories/filing.repository.interface';
import { ITaxRecordRepository, TAX_RECORD_REPOSITORY } from '../../../api/src/domain/repositories/tax-record.repository.interface';

export interface GenerateReportJobData {
  type: 'tax_summary' | 'gst_summary';
  filingId?: string;
  taxRecordId?: string;
  userId: string;
  tenantId: string;
  assessmentYear: string;
}

@Processor(QUEUES.REPORT_GENERATION, { concurrency: 2 })
export class ReportGeneratorWorker extends WorkerHost {
  private readonly logger = new Logger(ReportGeneratorWorker.name);
  private readonly r2: S3Client;

  constructor(
    private readonly config: AppConfigService,
    @Inject(FILING_REPOSITORY) private readonly filingRepo: IFilingRepository,
    @Inject(TAX_RECORD_REPOSITORY) private readonly taxRepo: ITaxRecordRepository,
  ) {
    super();
    this.r2 = new S3Client({
      region: 'auto',
      endpoint: config.r2Endpoint,
      credentials: {
        accessKeyId: config.r2AccessKey,
        secretAccessKey: config.r2SecretKey,
      },
    });
  }

  async process(job: Job<GenerateReportJobData>): Promise<{ objectKey: string }> {
    const { type, taxRecordId, filingId, userId, tenantId, assessmentYear } = job.data;
    this.logger.log(`[Job ${job.id}] Generating ${type} for user ${userId}`);
    await job.updateProgress(10);

    // ── 1. Fetch data ──────────────────────────────────────────────────────────
    const taxRecord = taxRecordId ? await this.taxRepo.findById(taxRecordId, tenantId) : null;
    await job.updateProgress(30);

    // ── 2. Generate PDF ────────────────────────────────────────────────────────
    const pdfBuffer = await this.generatePdf(type, { taxRecord, assessmentYear });
    await job.updateProgress(60);

    // ── 3. Upload to R2 ────────────────────────────────────────────────────────
    const objectKey = `${tenantId}/${userId}/reports/${assessmentYear}_${type}_${Date.now()}.pdf`;
    await this.r2.send(new PutObjectCommand({
      Bucket: this.config.r2Bucket,
      Key: objectKey,
      Body: pdfBuffer,
      ContentType: 'application/pdf',
    }));
    await job.updateProgress(80);

    // ── 4. Persist objectKey back to the Filing entity ─────────────────────────
    if (filingId) {
      const filing = await this.filingRepo.findById(filingId, tenantId);
      if (filing) {
        const withReport = filing.markReadyToFile(objectKey);
        await this.filingRepo.update(withReport);
        this.logger.log(`[Job ${job.id}] Filing ${filingId} marked READY_TO_FILE`);
      }
    }

    // ── 5. Progress completed ──────────────────────────────────────────────────
    await job.updateProgress(100);

    this.logger.log(`[Job ${job.id}] ✅ Report generated: ${objectKey}`);
    return { objectKey };
  }

  // ─── PDF generation using PDFKit ──────────────────────────────────────────────
  private async generatePdf(type: string, data: any): Promise<Buffer> {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const PDFDocument = require('pdfkit');
    const chunks: Buffer[] = [];
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // ── Header ─────────────────────────────────────────────────────────────
      doc.fontSize(24).fillColor('#2563eb').text('TaxAI', 40, 40);
      doc.fontSize(10).fillColor('#6b7280').text('AI-Powered Tax & Compliance Platform', 40, 70);
      doc.moveTo(40, 90).lineTo(555, 90).strokeColor('#e5e7eb').stroke();

      if (type === 'tax_summary' && data.taxRecord) {
        this.writeTaxSummary(doc, data.taxRecord, data.assessmentYear);
      } else {
        this.writeBlankReport(doc, type, data.assessmentYear);
      }

      // ── Footer ─────────────────────────────────────────────────────────────
      const pageHeight = doc.page.height;
      doc.fontSize(8).fillColor('#9ca3af')
        .text(
          `Generated by TaxAI on ${new Date().toLocaleDateString('en-IN')} | Computer-generated document.`,
          40, pageHeight - 40, { align: 'center', width: 515 },
        );
      doc.end();
    });
  }

  private writeTaxSummary(doc: any, taxRecord: any, assessmentYear: string): void {
    const best = taxRecord.recommendedRegime === 'old'
      ? taxRecord.oldRegimeResult
      : taxRecord.newRegimeResult;

    doc.moveDown(1);
    doc.fontSize(18).fillColor('#111827').text('Tax Summary Report', { align: 'center' });
    doc.fontSize(12).fillColor('#6b7280').text(`Assessment Year: ${assessmentYear}`, { align: 'center' });
    doc.moveDown(1);

    // Recommended regime banner
    const bannerY = doc.y;
    doc.rect(60, bannerY, 475, 30)
       .fill(taxRecord.recommendedRegime === 'new' ? '#dcfce7' : '#dbeafe');
    doc.fontSize(11).fillColor('#166534')
       .text(
         `✓ ${taxRecord.recommendedRegime === 'new' ? 'New' : 'Old'} Regime Recommended — Saves Rs. ${(taxRecord.taxSavingBySwitch ?? 0).toLocaleString('en-IN')}`,
         75, bannerY + 10,
       );
    doc.moveDown(1.5);

    // Income & tax breakdown
    this.writeSection(doc, 'Income & Tax Breakdown');
    this.writeRow(doc, 'Gross Income',          `Rs. ${(best.grossIncome ?? 0).toLocaleString('en-IN')}`);
    this.writeRow(doc, 'Total Deductions',       `Rs. ${(best.totalDeductions ?? 0).toLocaleString('en-IN')}`);
    this.writeRow(doc, 'Taxable Income',         `Rs. ${(best.taxableIncome ?? 0).toLocaleString('en-IN')}`, true);
    doc.moveDown(0.3);
    this.writeRow(doc, 'Tax Before Cess',        `Rs. ${(best.taxBeforeCess ?? 0).toLocaleString('en-IN')}`);
    this.writeRow(doc, '87A Rebate',             `-Rs. ${(best.section87ARebate ?? 0).toLocaleString('en-IN')}`);
    this.writeRow(doc, 'Surcharge',              `Rs. ${(best.surcharge ?? 0).toLocaleString('en-IN')}`);
    this.writeRow(doc, 'Health & Education Cess','Rs. ' + (best.cess ?? 0).toLocaleString('en-IN'));
    doc.moveDown(0.3);
    this.writeRow(doc, 'TOTAL TAX PAYABLE',      `Rs. ${(best.totalTax ?? 0).toLocaleString('en-IN')}`, true, '#dc2626');
    this.writeRow(doc, 'Effective Tax Rate',     `${best.effectiveTaxRate ?? 0}%`);

    // Regime comparison
    doc.moveDown(1);
    this.writeSection(doc, 'Regime Comparison');
    this.writeRow(doc, 'Old Regime Tax', `Rs. ${(taxRecord.oldRegimeResult?.totalTax ?? 0).toLocaleString('en-IN')}`);
    this.writeRow(doc, 'New Regime Tax', `Rs. ${(taxRecord.newRegimeResult?.totalTax ?? 0).toLocaleString('en-IN')}`);

    // Filing readiness
    doc.moveDown(1);
    this.writeSection(doc, 'Filing Readiness');
    this.writeRow(doc, 'Readiness Score', `${taxRecord.filingReadinessScore ?? 0}/100`);

    if (taxRecord.missingDocuments?.length) {
      doc.fontSize(9).fillColor('#dc2626')
         .text(`Missing: ${taxRecord.missingDocuments.join(', ')}`, 75, doc.y).moveDown(0.4);
    }

    // Deduction suggestions (slice to 3 to guarantee A4 single-page fit)
    if (taxRecord.deductionSuggestions?.length) {
      doc.moveDown(1);
      this.writeSection(doc, 'Tax-Saving Opportunities');
      for (const s of taxRecord.deductionSuggestions.slice(0, 3)) {
        this.writeRow(doc, `Section ${s.section}`, `Save Rs. ${(s.potentialSaving ?? 0).toLocaleString('en-IN')}`);
        const cleanAction = (s.actionRequired ?? '').replace(/₹/g, 'Rs. ');
        doc.fontSize(9).fillColor('#6b7280').text(cleanAction, 75, doc.y).moveDown(0.2);
      }
    }
  }

  private writeBlankReport(doc: any, type: string, assessmentYear: string): void {
    doc.moveDown(2);
    doc.fontSize(18).fillColor('#111827')
       .text(type.replace(/_/g, ' ').toUpperCase(), { align: 'center' });
    doc.fontSize(12).fillColor('#6b7280').text(`Assessment Year: ${assessmentYear}`, { align: 'center' });
    doc.moveDown(2);
    doc.fontSize(11).fillColor('#374151').text('No data available. Please calculate your tax first.');
  }

  private writeSection(doc: any, title: string): void {
    doc.fontSize(12).fillColor('#1f2937').text(title, 60, doc.y, { underline: true });
    doc.moveDown(0.4);
  }

  private writeRow(doc: any, label: string, value: string, bold = false, valueColor = '#111827'): void {
    const y = doc.y;
    doc.fontSize(10).fillColor('#4b5563').text(label, 60, y);
    doc.fontSize(10).fillColor(valueColor)
       .font(bold ? 'Helvetica-Bold' : 'Helvetica')
       .text(value, 350, y, { align: 'right', width: 195 });
    doc.font('Helvetica').moveDown(0.4);
  }
}