import { Processor, WorkerHost } from '@nestjs/bullmq';
import { Job } from 'bullmq';
import { Inject, Logger } from '@nestjs/common';
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import { QUEUES, JOBS } from '@taxai/shared';
import { AppConfigService } from '../../../api/src/infrastructure/config/app-config.service';
import { IFilingRepository, FILING_REPOSITORY } from '../../../api/src/domain/repositories/filing.repository.interface';
import { ITaxRecordRepository, TAX_RECORD_REPOSITORY } from '../../../api/src/domain/repositories/tax-record.repository.interface';

export interface GenerateReportJobData {
  type: 'tax_summary' | 'gst_summary';
  filingId?: string;
  taxRecordId?: string;
  userId: string;
  tenantId: string;
  assessmentYear: string;
}

@Processor(QUEUES.REPORT_GENERATION, { concurrency: 2 })
export class ReportGeneratorWorker extends WorkerHost {
  private readonly logger = new Logger(ReportGeneratorWorker.name);
  private readonly r2: S3Client;

  constructor(
    private readonly config: AppConfigService,
    @Inject(FILING_REPOSITORY) private readonly filingRepo: IFilingRepository,
    @Inject(TAX_RECORD_REPOSITORY) private readonly taxRepo: ITaxRecordRepository,
  ) {
    super();
    this.r2 = new S3Client({
      region: 'auto',
      endpoint: config.r2Endpoint,
      credentials: {
        accessKeyId: config.r2AccessKey,
        secretAccessKey: config.r2SecretKey,
      },
    });
  }

  async process(job: Job<GenerateReportJobData>): Promise<{ objectKey: string; publicUrl: string }> {
    const { type, taxRecordId, userId, tenantId, assessmentYear } = job.data;
    this.logger.log(`[Job ${job.id}] Generating ${type} report for user ${userId}`);

    await job.updateProgress(10);

    // Fetch data
    const taxRecord = taxRecordId ? await this.taxRepo.findById(taxRecordId, tenantId) : null;
    await job.updateProgress(30);

    // Generate PDF buffer
    const pdfBuffer = await this.generatePdf(type, { taxRecord, assessmentYear, userId });
    await job.updateProgress(70);

    // Upload to R2
    const objectKey = `${tenantId}/${userId}/reports/${assessmentYear}_${type}_${Date.now()}.pdf`;
    await this.r2.send(new PutObjectCommand({
      Bucket: this.config.r2Bucket,
      Key: objectKey,
      Body: pdfBuffer,
      ContentType: 'application/pdf',
    }));

    await job.updateProgress(100);
    const publicUrl = `${this.config.r2PublicUrl}/${objectKey}`;
    this.logger.log(`[Job ${job.id}] Report uploaded: ${objectKey}`);

    return { objectKey, publicUrl };
  }

  private async generatePdf(type: string, data: any): Promise<Buffer> {
    // PDFKit usage — install: npm install pdfkit @types/pdfkit
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const PDFDocument = require('pdfkit');
    const chunks: Buffer[] = [];

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // ── Header ─────────────────────────────────────────────────────────────
      doc.fontSize(24).fillColor('#2563eb').text('TaxAI', 50, 50);
      doc.fontSize(10).fillColor('#6b7280').text('AI-Powered Tax & Compliance Platform', 50, 80);
      doc.moveTo(50, 100).lineTo(545, 100).strokeColor('#e5e7eb').stroke();

      if (type === 'tax_summary' && data.taxRecord) {
        this.writeTaxSummary(doc, data.taxRecord, data.assessmentYear);
      } else {
        this.writeBlankReport(doc, type, data.assessmentYear);
      }

      // ── Footer ─────────────────────────────────────────────────────────────
      const pageHeight = doc.page.height;
      doc.fontSize(8).fillColor('#9ca3af')
        .text(
          `Generated by TaxAI on ${new Date().toLocaleDateString('en-IN')} | This is a computer-generated document.`,
          50, pageHeight - 50, { align: 'center' },
        );

      doc.end();
    });
  }

  private writeTaxSummary(doc: any, taxRecord: any, assessmentYear: string): void {
    const best = taxRecord.recommendedRegime === 'old'
      ? taxRecord.oldRegimeResult
      : taxRecord.newRegimeResult;

    // ── Title ───────────────────────────────────────────────────────────────
    doc.moveDown(2);
    doc.fontSize(18).fillColor('#111827').text(`Tax Summary Report`, { align: 'center' });
    doc.fontSize(12).fillColor('#6b7280').text(`Assessment Year: ${assessmentYear}`, { align: 'center' });
    doc.moveDown(2);

    // ── Recommended Regime Banner ────────────────────────────────────────────
    const bannerColor = taxRecord.recommendedRegime === 'new' ? '#dcfce7' : '#dbeafe';
    const bannerText = taxRecord.recommendedRegime === 'new' ? 'New Regime Recommended' : 'Old Regime Recommended';
    doc.rect(50, doc.y, 495, 40).fill(bannerColor);
    doc.fontSize(14).fillColor('#166534')
      .text(`✓ ${bannerText} — Saves ₹${taxRecord.taxSavingBySwitch?.toLocaleString('en-IN') || 0}`, 70, doc.y - 30);
    doc.moveDown(2);

    // ── Income Summary ───────────────────────────────────────────────────────
    this.writeSection(doc, 'Income & Tax Breakdown');
    this.writeRow(doc, 'Gross Income', `₹${best.grossIncome?.toLocaleString('en-IN') || 0}`);
    this.writeRow(doc, 'Total Deductions', `₹${best.totalDeductions?.toLocaleString('en-IN') || 0}`);
    this.writeRow(doc, 'Taxable Income', `₹${best.taxableIncome?.toLocaleString('en-IN') || 0}`, true);
    doc.moveDown();
    this.writeRow(doc, 'Tax Before Cess', `₹${best.taxBeforeCess?.toLocaleString('en-IN') || 0}`);
    this.writeRow(doc, '87A Rebate', `-₹${best.section87ARebate?.toLocaleString('en-IN') || 0}`);
    this.writeRow(doc, 'Surcharge', `₹${best.surcharge?.toLocaleString('en-IN') || 0}`);
    this.writeRow(doc, 'Health & Education Cess (4%)', `₹${best.cess?.toLocaleString('en-IN') || 0}`);
    doc.moveDown();
    this.writeRow(doc, 'TOTAL TAX PAYABLE', `₹${best.totalTax?.toLocaleString('en-IN') || 0}`, true, '#dc2626');
    this.writeRow(doc, 'Effective Tax Rate', `${best.effectiveTaxRate || 0}%`);

    // ── Regime Comparison ───────────────────────────────────────────────────
    doc.moveDown(2);
    this.writeSection(doc, 'Regime Comparison');
    this.writeRow(doc, 'Old Regime Tax', `₹${taxRecord.oldRegimeResult?.totalTax?.toLocaleString('en-IN') || 0}`);
    this.writeRow(doc, 'New Regime Tax', `₹${taxRecord.newRegimeResult?.totalTax?.toLocaleString('en-IN') || 0}`);

    // ── Filing Readiness ────────────────────────────────────────────────────
    doc.moveDown(2);
    this.writeSection(doc, 'Filing Readiness');
    this.writeRow(doc, 'Readiness Score', `${taxRecord.filingReadinessScore || 0}/100`);
    if (taxRecord.missingDocuments?.length) {
      doc.fontSize(10).fillColor('#dc2626')
        .text(`Missing: ${taxRecord.missingDocuments.join(', ')}`, { indent: 20 });
    }
  }

  private writeBlankReport(doc: any, type: string, assessmentYear: string): void {
    doc.moveDown(2);
    doc.fontSize(18).fillColor('#111827').text(`${type.replace('_', ' ').toUpperCase()} REPORT`, { align: 'center' });
    doc.fontSize(12).fillColor('#6b7280').text(`Assessment Year: ${assessmentYear}`, { align: 'center' });
    doc.moveDown(2);
    doc.fontSize(11).fillColor('#374151').text('No data available for this report. Please calculate your tax first.');
  }

  private writeSection(doc: any, title: string): void {
    doc.fontSize(13).fillColor('#1f2937').text(title, { underline: true });
    doc.moveDown(0.5);
  }

  private writeRow(doc: any, label: string, value: string, bold = false, valueColor = '#111827'): void {
    const y = doc.y;
    doc.fontSize(10).fillColor('#4b5563').text(label, 60, y);
    doc.fontSize(10).fillColor(valueColor)
      .font(bold ? 'Helvetica-Bold' : 'Helvetica')
      .text(value, 350, y, { align: 'right', width: 195 });
    doc.font('Helvetica').moveDown(0.4);
  }
}